# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pranjal For Lit
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  An unbiased show of literary and decorative merit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  HaoZeke
author: Rohit Goswami

# Build settings
source: src
destination: public
markdown: kramdown
plugins:
  - jekyll-feed
  - hawkins
  - jekyll-assets

assets:
  compress:
    css: false
    js: false
  autowrite: true
  cache: .cache
  prefix: "/assets"
  digest: false
  sources:
    - _assets/js
    - _assets/img
    - _assets/fonts
    - _assets/styles
    - _assets/styles/bulma
    - _assets/styles/bulma/sass/
    - _assets/styles/bulma/sass/base/
    - _assets/styles/bulma/sass/components/
    - _assets/styles/bulma/sass/elements/
    - _assets/styles/bulma/sass/grid/
    - _assets/styles/bulma/sass/layout/
    - _assets/styles/bulma/sass/utilities/
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
  features:
    liquid: false
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include : ['_pages']

# File Handling
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - src/.cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - .cache
  - .gz